# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"

install:
  - pip install -U -r requirements/requirements.txt
  - pip install -U -r requirements/test_requirements.txt
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - py.test --flake  --cov-report term --cov pyzillow test/

after_success:
  - coveralls
